<a href="https://colab.research.google.com/github/ai7dnn/2024-python/blob/main/2024_python_finaltest_core.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 학습 정리

- shift + Enter : 실행 후 다음 셀로 이동, 다음 셀이 없으면 생성
- ctrl + Enter : 현재 셀만 실행
- alt + Enter : 현재 셀 실행 후 다음 셀 생성

## 현재 사용 파이썬 점검

In [1]:
import sys
sys.version

'3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]'

In [2]:
import site
site.getsitepackages()

['/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.10/dist-packages']

# 기말시험

![image.png]()

# 모임 자료형

In [ ]:
# %% list tuple
lst = [10, 20, 30]
print(lst, type(lst))

[10, 20, 30] <class 'list'>

In [3]:
lst = [1, 3.92, 3 > 4, 'list', [1, 2, 3]]
print(lst)
lst.append('py')
print(lst)

[1, 3.92, False, 'list', [1, 2, 3]]
[1, 3.92, False, 'list', [1, 2, 3], 'py']

In [4]:
print(lst)
print(f'lst[0] = {lst[0]}')
print(f'lst[4] = {lst[4]}')

[1, 3.92, False, 'list', [1, 2, 3], 'py']
lst[0] = 1
lst[4] = [1, 2, 3]

In [5]:
lst[1] = 'java'
print(lst)

[1, 'java', False, 'list', [1, 2, 3], 'py']

In [6]:
# %% tuple
tpl = (10, 20, 30)
print(tpl, type(tpl))

(10, 20, 30) <class 'tuple'>

In [8]:
tpl = 1, 3.92, 3 > 4, 'tuple'
print(tpl, type(tpl))

print(tpl[0])
print(tpl[3])

(1, 3.92, False, 'tuple') <class 'tuple'>
1
tuple

In [9]:
tpl[1] = 100
# tpl.append('py') # 오류발생

TypeError: 'tuple' object does not support item assignment

In [10]:
# %% 사전 dict
mart = {'라면': 1200, '음료수': 1500, '과자': 800}
print(mart, type(mart))

{'라면': 1200, '음료수': 1500, '과자': 800} <class 'dict'>

In [11]:
mart2 = dict([['라면', 1200], ['음료수', 1500], ['과자', 800]])
mart2

{'라면': 1200, '음료수': 1500, '과자': 800}

In [12]:
mart3 = dict((['라면', 1200], ['음료수', 1500], ['과자', 800]))
mart3

{'라면': 1200, '음료수': 1500, '과자': 800}

In [15]:
# 딕셔너리 참조
print(mart['라면'])
print(mart['음료수'])
print(mart)

1200
1500
{'라면': 1200, '음료수': 1500, '과자': 800}

In [16]:
mart['과자'] = 900
mart['삼각김밥'] = 1700
print(mart)

{'라면': 1200, '음료수': 1500, '과자': 900, '삼각김밥': 1700}

In [17]:
print(mart.keys())
print(mart.values())
print(mart.items())

dict_keys(['라면', '음료수', '과자', '삼각김밥'])
dict_values([1200, 1500, 900, 1700])
dict_items([('라면', 1200), ('음료수', 1500), ('과자', 900), ('삼각김밥', 1700)])

In [18]:
for i in mart:
    print(i)

라면
음료수
과자
삼각김밥

In [19]:
for i in mart:
    print(i, mart[i])

라면 1200
음료수 1500
과자 900
삼각김밥 1700

In [ ]:
for i in mart.values():
    print(i)

1200
1500
900
1700

In [ ]:
for i in mart.items():
    print(i)

('라면', 1200)
('음료수', 1500)
('과자', 900)
('삼각김밥', 1700)

In [ ]:
for i in mart.items():
    print(i[0], i[1])

라면 1200
음료수 1500
과자 900
삼각김밥 1700

In [20]:
for k, v in mart.items():
    print(k, v)

라면 1200
음료수 1500
과자 900
삼각김밥 1700

In [25]:
a, b = 1, 2
b

2

In [29]:
# %% set
basket = {'apple', 'orange', 'apple', 'pear'}
print(basket)

basket.add('banana')
print(basket)

# basket[0] # 오류

{'apple', 'orange', 'pear'}
{'apple', 'orange', 'pear', 'banana'}

In [30]:
myset = {1, 2, 3.4}
print(myset)
myset.add(5)
print(myset)
myset.add(5)
myset

{1, 2, 3.4}
{1, 2, 3.4, 5}

{1, 2, 3.4, 5}

In [33]:
# 수정가능한 자료는 집합의 원소로 불가
# myset.add([1, 2]) # 오류
myset.add((1, 2))
print(myset)

{1, 2, (1, 2), 3.4, 5}

In [34]:
# 집합은 수정가능한(mutable) 자료형을 원소가 될 수 없음
myset.add([1, 2])

TypeError: unhashable type: 'list'

In [35]:
# 리스트는 수정가능한(mutable) 자료형
lst = [1, 2, 3]
print(id(lst))
print(lst)

lst.append(4)
print(id(lst))
print(lst)

140227207706880
[1, 2, 3]
140227207706880
[1, 2, 3, 4]

## 함수 기초

In [37]:
# %%
print('안녕, 현수!')
print('안녕, 수희!')
print('안녕, 지수!')

# %% 함수
def greet():
    print('안녕, 현수!')
    print('안녕, 수희!')
    print('안녕, 지수!')

# greet()

안녕, 현수!
안녕, 수희!
안녕, 지수!

In [38]:
# %%
def greet(name):
    print(f'안녕, {name}!')

greet('현수')
greet('수희')
greet('지수')
greet('모든 친구들')

안녕, 현수!
안녕, 수희!
안녕, 지수!
안녕, 모든 친구들!

In [40]:
# %% 반환 값 None
def greet(name):
    print(f'안녕, {name}!')

print(greet('모든 친구들'))

안녕, 모든 친구들!
None

In [45]:
# %%
def toArea(pg):
    return pg * 3.3

print(toArea(16))

pg = 24
print(f'{pg} 평은 {toArea(pg):.3f} 제곱미터')
pg = 32
print(f'{pg} 평은 {toArea(pg):.2f} 제곱미터')

52.8
24 평은 79.200 제곱미터
32 평은 105.60 제곱미터

In [48]:
def myfun(a, b, c=2, d=3):
# def myfun(a, b, c, d):
	return a * b + c - d

print(myfun(2, 3))
print(myfun(3, 4, 5, 1))
print(myfun(3, 4, d=5, c=1))

5
16
8

#### 함수도 객체

In [51]:
# 함수 정의
def hello():
    print('안녕')

print(type(hello))

<class 'function'>

In [54]:
# 정의된 함수 주소 출력
print(hello)
print(id(hello))

<function hello at 0x7f8930e99120>
140227207860512

In [56]:
# 함수 호출
print(hello())

# 함수 대입
my_hello = hello
my_hello()

id(my_hello), id(hello)

안녕
None
안녕

(140227207860512, 140227207860512)

In [57]:
# %% 람다 함수 정의
lambda : print('안녕')

In [58]:
# 람다 함수 정의와 호출
(lambda : print('안녕'))()

안녕

In [59]:
my_hello = lambda : print('안녕')
my_hello()

안녕

In [60]:
print(my_hello, type(my_hello))
my_hello()

<function <lambda> at 0x7f8930e99c60> <class 'function'>
안녕

In [61]:
# 람다 함수 정의
pyeong_to_ms = lambda pg: f'{pg} 평은 {pg*3.3:.2f} 제곱미터 입니다.'

# 람다 함수 호출
print(pyeong_to_ms(24))
print(pyeong_to_ms(32))

24 평은 79.20 제곱미터 입니다.
32 평은 105.60 제곱미터 입니다.

# 리스트 컴프리헨션

In [ ]:
# 간단한 리스트 컴프리헨션
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [62]:
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
# 연산식의 다양한 표현
print([i + 1 for i in range(5)])
print([i ** 2 for i in range(5)])
print([pow(i, 3) for i in range(5)])

[1, 2, 3, 4, 5]
[0, 1, 4, 9, 16]
[0, 1, 8, 27, 64]

In [ ]:
# 간단한 리스트 컴프리헨션
lst1 = [i for i in range(10)]
lst2 = [[i, i+1] for i in range(5)]
lst3 = [{i+1: str(i+1) + '월'} for i in range(5)]

print(lst1)
print(lst2)
print(lst3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]]
[{1: '1월'}, {2: '2월'}, {3: '3월'}, {4: '4월'}, {5: '5월'}]

In [67]:
[{i+1: str(i+1) + '월'} for i in range(5)][0]

{1: '1월'}

In [ ]:
[[i, i+1] for i in range(5)]

[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]]

In [71]:
[[i, i+1] for i in range(5)][2]

[2, 3]

In [70]:
[[i, i+1] for i in range(5)][2][0]

2

In [72]:
# 반복 전체의 항목을 리스트에 삽입
print([i for i in range(6)])
# 반복 항목 중에서 짝수를 리스트에 삽입
print([i for i in range(6) if i%2 == 0])
# 반복 항목 중에서 홀수를 리스트에 삽입
print([i for i in range(6) if i%2 == 1])

[0, 1, 2, 3, 4, 5]
[0, 2, 4]
[1, 3, 5]

In [73]:
i = 1
'even' if i%2 == 0 else 'odd'

'odd'

In [ ]:
# 리스트에 짝수면 0, 홀수면 1을 삽입
[0 if i%2 == 0 else 1 for i in range(10)]

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

In [74]:
# 리스트에 짝수면 even, 홀수면 odd를 삽입
['even' if i%2 == 0 else 'odd' for i in range(10)]

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [75]:
# 고정된 항목의 중첩된 2차원 리스트
[[1, 2] for i in range(4)] # 고정된 항목

[[1, 2], [1, 2], [1, 2], [1, 2]]

In [76]:
# 변화되는 중첩된 2차원 리스트
[[i, i+1, i+2] for i in range(3)]

[[0, 1, 2], [1, 2, 3], [2, 3, 4]]

In [ ]:
# 다양한 자료형으로 구성된 리스트의 항목
print([(i, i+1) for i in range(4)])
print([{i, i+1} for i in range(4)])
print([{i: i**2} for i in range(4)])

[(0, 1), (1, 2), (2, 3), (3, 4)]
[{0, 1}, {1, 2}, {2, 3}, {3, 4}]
[{0: 0}, {1: 1}, {2: 4}, {3: 9}]

In [79]:
[{i: i**2} for i in range(4)][1]

{1: 1}

In [80]:
[[k for k in range(1, 3)] for i in range(4)]

[[1, 2], [1, 2], [1, 2], [1, 2]]

# map

In [ ]:
help(map)

Help on class map in module builtins:

class map(object)
 |  map(func, *iterables) --> map object
 |
 |  Make an iterator that computes the function using arguments from
 |  each of the iterables.  Stops when the shortest iterable is exhausted.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.

In [ ]:
pow(3, 4)

81

In [88]:
my_map = map(pow, [1, 2, 3], [2, 2, 2])
my_map

In [89]:
list(my_map)

[1, 4, 9]

In [90]:
[{i+1: str(i+1) + '월'} for i in range(5)]

[{1: '1월'}, {2: '2월'}, {3: '3월'}, {4: '4월'}, {5: '5월'}]

In [91]:
list(range(1, 5))

[1, 2, 3, 4]

In [92]:
# map에서 사용자 정의 함수 활용
def my_mult(x, y):
    return x * y

list(map(my_mult, range(1, 5), range(1, 5)))

[1, 4, 9, 16]

In [93]:
# map에서 람다 함수 활용
list(map(lambda inch: inch * 2.54, range(6)))

[0.0, 2.54, 5.08, 7.62, 10.16, 12.7]

In [95]:
# map에서 메소드 활용
list(map(str.isalpha, 'py13'))

[True, True, False, False]

In [94]:
str.isalpha('3')

False

In [99]:
# 내장 함수 int() 인자 하나 또는 둘
print(int('10'))
print(int('10', 16)) # 16진수 '10'을 10진수로 출력

10
16

In [100]:
# map에서 내장 함수 int() 활용
print(list(map(int, [3, 5, 11])))
print(list(map(int, ['1', '5', '11'], [2, 8, 16])))

[3, 5, 11]
[1, 5, 17]

In [ ]:
# map에서 중첩되게 map() 사용
s = [1, 5, 11]
list(map(str, [1, 5, 11]))

['1', '5', '11']

In [101]:
list(map(int, map(str, [1, 5, 11]), [2, 8, 16]))

[1, 5, 17]

# zip enumerate

In [102]:
a = [1, 2, 3]
b = ['JAN', 'FEB', 'MAR']
zip(a, b)

In [ ]:
list(zip(a, b))

[(1, 'JAN'), (2, 'FEB'), (3, 'MAR')]

In [ ]:
dict(zip(a, b))

{1: 'JAN', 2: 'FEB', 3: 'MAR'}

In [103]:
dict(zip(a, b))[2]

'FEB'

In [ ]:
b

['JAN', 'FEB', 'MAR']

In [108]:
for i, month in enumerate(b, 4):
    print(f'{i} {month}')

4 JAN
5 FEB
6 MAR

#### 한 학기동안 수고 많았습니다.